# Generated by Django 2.2.17 on 2020-12-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghfg', '0002_auto_20201207_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userss',
            name='gjhgjhg',
        ),
        migrations.RemoveField(
            model_name='userss',
            name='hfhgfhgf',
        ),
        migrations.RemoveField(
            model_name='userss',
            name='jhgjhghjghjg',
        ),
    ]
